### ISSUE TITLE
Telemetry - Airflow StatsD Prometheus improvements

### ISSUE THREAD

**Issue by tedmiston** [astronomerio/astronomer#104]

**Comment by tedmiston** [comment]
This task has been my biggest focus so far  — digging into Airflow and understanding how the integration with StatsD and statsd_exporter really work.  I've identified at least one related bug in Airflow that can be fixed as a PR already.

**Comment by ryw** [comment]
@tedmiston have you done any actual work on this that you can PR back to Airflow?

**Comment by ryw** [comment]
Issue moved to [astronomerio/incubator-airflow #26](https://github.com/astronomerio/incubator-airflow/issues/26) via [**ZenHub**](https://www.zenhub.com/)
