### ISSUE TITLE
Refactor to support new OAuth flow support in CLI

### ISSUE THREAD

**Issue by cwurtz** [astronomerio/astronomer#119]
Update `astro auth login` so it outputs a URL that direct the user to an orbit page to start the OAuth process.  After that URL output it should await input of a token that user will eventually receive after authenticating.

This token should then be saved to the global config.

Exact details still TBD, but currently it is expected that all registry auth functionality should be stripped out.  Depending on what options we have with docker auth, we'll either hardcode the username to something, and use the token as the password.  Alternatively if we can set or pass the encoded user/pass, we can just pass the token.

**Comment by ryw** [comment]
Issue moved to [astronomerio/astro-cli #75](https://github.com/astronomerio/astro-cli/issues/75) via [**ZenHub**](https://www.zenhub.com/)
