### ISSUE TITLE
Docs out of sync with repo?

### ISSUE THREAD

**Issue by c0bra** [astronomerio/astronomer#120]
The instructions here: https://open.astronomer.io/#start-from-existing-code  refer to a `start` script and an `.astro` directory that should be part of the repo but they don't appear to exist, currently. Have things gotten out of sync or am I confused?

My main problem is I need to install python modules and apk packages and can't seem to do it using the requirements.txt/packages.txt files on docker-compose up/down.

**Comment by tedmiston** [comment]
Hey @c0bra - looking into this for you now.  We currently deploy the docs sites manually so it's possible the website is lagging the master branch of the repo.

**Comment by c0bra** [comment]
Appreciate it, thanks. I've moved back to pukel's docker image for now.

**Comment by tedmiston** [comment]
@c0bra I ran a fresh deploy.  Can you take a look at the same URL now and see if looks good to you?

I think the confusing bit might be that we had the start script and .astro stuff in here and then moved that into [astro-cli](https://github.com/astronomerio/astro-cli/) to automate it, but the astro-cli is only part of Astronomer EE, not Astronomer Open today.  [@andscoop @schnie should we remove this part of the Open docs?]

As far as the 2 Airflow examples go, you should be able to run `docker-compose up` in examples/airflow-core or examples/airflow-enterprise.

**Comment by schnie** [comment]
Yea, we should remove any references to the old scripts from the open docs. `docker compose up` is the recommended way to fire the images up now. We just don't support a way to develop on Airflow without the CLI right now.

**Comment by c0bra** [comment]
@tedmiston if you mean this url: https://open.astronomer.io/#start-from-existing-code, then it's still referencing a `./start` script, as well as `Dockerfile.astro` and the `.astro` directory.

It sounds like you're saying those things only apply to EE and not Open.

**Comment by ryw** [comment]
@cwurtz can you fix docs, then close this issue?

**Comment by schnie** [comment]
We should push the idea of our CLI being a great way to easily get started with airflow, in addition to supporting our enterprise product. This way we don't have to maintain multiple versions of these scripts inside the open project, as well as our CLI. It'd be nice to just keep our development sauce in one place, rather than in 2 or 3 places.

**Comment by cwurtz** [comment]
For context, I have a PR for the doc updates and adding the start/stop/pause scripts back (https://github.com/astronomerio/astronomer/pull/122#issuecomment-398953182).  In updating the docs I realized there isn't a concise way to start the platform without the start script or using the CLI.

**Comment by schnie** [comment]
I just think we're making it harder on ourselves as we add features to local development and we're limited to using bash, as well as duplicating that functionality in the CLI. I know we currently only push our CLI to EE customers, but we could start focusing effort on the local development experience, even if people are just using it to run airflow and develop locally. 

Maybe we could make the EE features an add-on to the CLI or something too, so it doesn't clutter the open users experience.

I see our open project as just a place to bundle and showcase the components of the platform, with the focus being on the images. I see the examples just as a way to demonstrate how the components interact with each other.

@cwurtz @ryw @andscoop what do you guys think?

**Comment by cwurtz** [comment]
Regardless of the ideal way to support this going forward, for the time being (and last few months) there isn't a way to use the `airflow core` example with any custom deps short of manually creating the Dockerfile that uses the onbuild base and overwriting the image or tag ENV to use it with docker-compose.  I can update the docs to outline this process, but it's easier to just use the start script.

**Comment by c0bra** [comment]
Just a note: I appreciate seeing this stuff being discussed in the open.

Good job! 👍

**Comment by cwurtz** [comment]
Sorry dropped the ball on keeping this up to date.  I think we'll end up keeping the start script out of this repo so we can more easily keep things up to date by moving the functionality of running the docker images for open via our CLI.  For the time being I forked my change here to my GH as branches in the astronomerio repos get cleaned up when they get stale.  
https://github.com/cwurtz/astronomer/blob/start_script/examples/airflow-core

Should just be matter of running `/path/to/repo/examples/airflow-core/start /path/to/airflow_home`

I'll change my commit this week to just get the docs up to date.

**Comment by ryw** [comment]
@cwurtz can you knock this out

**Comment by ryw** [comment]
@cwurtz reminder to knock this out please
