### ISSUE TITLE
Add support for multiple airflow versions

### ISSUE THREAD

**Issue by andscoop** [astronomerio/astronomer#131]
We will soon need to support at a minimum  incubator-airflow 1.9 and 1.10. We will need to make changes to the build scripts as well as potential changes to the airflow Dockerfile and directory structure.

**Comment by andscoop** [comment]
@schnie Can you link to other issue you have for modifying our /astronomer repo as we discussed yesterday?

**Comment by schnie** [comment]
@andscoop I haven't anything more specific than this one yet. Let's use this one to discuss full implementation, then break out into specific issues for v0.3.4 milestone.

I have some changes to this repo that separates the airflow build process out from the rest of the platform. I'll send a PR in a bit.

It will give us the ability to build for multiple airflow versions and each with their own `Dockerfile`. Right now I have it so all platform images are built and tagged as normal: `astronomerinc/ap-airflow:0.3.3` or `astronomerinc/ap-airflow:0.3.3-rc.1`. Airflow images are now tagged combining airflow + astro release: `astronomerinc/ap-airflow:1.10.0-0.3.3` or `astronomerinc/ap-airflow:1.10.0-0.3.3-rc.1`.

Thinking we just keep the default value in the `values.yaml` for the airflow chart in sync with whatever the latest is. Houston will prob need to start tracking and passing along the chosen version for deployments though. Something like a dropdown in the UI during creation, and a flag in the CLI.

@andscoop @tedmiston @cwurtz what you guys think?

**Comment by tedmiston** [comment]
Everything above sounds good to me.

**Comment by tedmiston** [comment]
Actually, what do you guys think of flipping the version string config to be like this?

```
<organization>/<component>:<platform version>-<airflow version>
```

I got that idea from the python docker image e.g., `python:3-alpine` but many others use the same.

The idea being that our platform version encompasses all components in the platform so it should take precedence over the version of an individual component like Airflow.

I think this:

```
astronomerinc/ap-airflow:0.3.3-1.9.0
astronomerinc/ap-airflow:0.3.3-1.10.0
```

is clearer than this:

```
astronomerinc/ap-airflow:1.9.0-0.3.3
astronomerinc/ap-airflow:1.10.0-0.3.3
```

Plus it sorts Airflow subversions for a platform release together.

**Comment by cwurtz** [comment]
To me it's kinda iffy.  It's not like the Docker image is some software we created that is bundling a library or additional dep.  It is a slightly modified version of Airflow, which is ~80% of the image name.  I really like that when sorted, putting astro first will keep things in order, but I feel like the `airflow` part of `ap-airflow` leads me to think the number that follows will be the airflow version, not the platform version.

**Comment by andscoop** [comment]
My vote is `${ASTRONOMER_VERSION}-${AIRFLOW_VERSION}` as it will begin to make more sense once when we cut new AIRFLOW_VERSION for future ASTRONOMER_VERSION. 

ie. 
ASTRONOMER_VERSION=0.3.4 might support AIRFLOW_VERSION=[1.8,1.9,1.10]
and
ASTRONOMER_VERSION=0.5 might support AIRFLOW_VERSION=[1.8,1.9,1.10,1.11]
and 
ASTRONOMER_VERSION=1.0 might support AIRFLOW_VERSION=[1.9,1.10,1.11, 2.0]

I would like the ability to visually sort and search for available Airflow versions within my platform release.

```
astronomerinc/ap-airflow:0.3.3-1.8.0
astronomerinc/ap-airflow:0.3.3-1.9.0
astronomerinc/ap-airflow:0.3.3-1.10.0

astronomerinc/ap-airflow:0.5.0-1.8.0
astronomerinc/ap-airflow:0.5.0-1.9.0
astronomerinc/ap-airflow:0.5.0-1.10.0
astronomerinc/ap-airflow:0.5.0-1.11.0

astronomerinc/ap-airflow:1.0-1.9.0
astronomerinc/ap-airflow:1.0-1.10.0
astronomerinc/ap-airflow:1.0-1.11.0
astronomerinc/ap-airflow:1.0-2.0
```

**Comment by cwurtz** [comment]
I have added support to Houston for changing some configs up based on the airflow version.  I currently only have an env variable set for`AIRFLOW__WEBSERVER__BASE_URL` to change it up to add the protocol for 1.10.  

Once we hammer out the image format I can have it use the correct default image as well.

**Comment by schnie** [comment]
@andscoop check @cwurtz comment above. What do you think about creating a new `airflowVersion` in `values.yaml` that we can pass in and key off that to determine which set and formatting of environment variables gets passed into the deployments?

**Comment by cwurtz** [comment]
I'm fine changing Houston up in favor of doing it in the helm chart

**Comment by andscoop** [comment]
Note to self - Will need to test to ensure that fernet keys are working appropriately

https://github.com/astronomerio/astro-cli/issues/123

**Comment by ryw** [comment]
Issue moved to [astronomerio/astronomer-ee #136](https://github.com/astronomerio/astronomer-ee/issues/136) via [**ZenHub**](https://www.zenhub.com/)
