### ISSUE TITLE
Code updated on deployments is not showing up

### ISSUE THREAD

**Issue by vparekh94** [astronomerio/astronomer#135]
When you run  `astro airflow deploy` to a pre-existing airflow deployment, code is not being updated.

The exact set up I had:

Spin up airflow 1
Spin up airflow 2

Deploy projectA to airflow1
Deploy projectB to airflow2
Make change to projectA, deploy to project1

Deploy projectB to airflow1.

airflow1 still shows code from project1.

**Comment by cwurtz** [comment]
Fix for this went out yesterday, will require a helm upgrade to fix
