### ISSUE TITLE
1. Airflow ElasticSearch Logs

### ISSUE THREAD

**Issue by gregbrunk** [astronomerio/astronomer#138]
As a deployment.user, I can see logs for the Webserver and Scheduler in the UI.

**Comment by schnie** [comment]
@tedmiston can you provide a little update on progress here? Anything blocking?

**Comment by tedmiston** [comment]
Sure - no blockers currently.  I believe we have all of the Houston work done and I now have testing and some tweaking left to do on the ElasticSearch side.
