### ISSUE TITLE
Standup Airflow Logs Infrastructure 

### ISSUE THREAD

**Issue by gregbrunk** [astronomerio/astronomer#139]
@schnie - this is a placeholder issue for the backend (pre-API) Airflow Logs 0.4 work. If you already have tickets where you are tracking this, please add those to the the Airflow Logs epic and the 0.4 milestone. Otherwise, swap out this description with some quick notes about what you're doing (helm, prometheus, Kube, etc). Also, feel free to use the "Move Issue" function in Zenhub if you'd rather this be in another repo.

**Comment by schnie** [comment]
Live on master.
