### ISSUE TITLE
Override airflow.cfg in UI or CLI

### ISSUE THREAD

**Issue by vparekh94** [astronomerio/astronomer#146]
As a user, I need to configure my SMTP settings (email alerts), settings for parallelism, and other ENV level settings without exposing credentials in my dockerfile.

It would be great to be able to do this through the UI.  We might need to provide an intermediate workaround as different versions of airflow have different names for `airflow.cfg` settings, but this is a pretty pressing need, as email notifications are one of airflow's best features.

**Comment by gregbrunk** [comment]
@vparekh94 - is this not something that can be configured in Airflow's UI?
@ryw - how should we prioritize this? We have a workspace settings style UX that is starting to evolve out of the roles and service token work being done this sprint. Should we slot it into one of those epics? (ie. https://github.com/astronomerio/astronomer/issues/143)

**Comment by vparekh94** [comment]
@greg do you think this is something that can be worked into the next milestone? We can get around most of the env settings needed, except for the smtp stuff (which requires credentials) which is also the most important one (based on our customers so far).

**Comment by vparekh94** [comment]
@ryw any update on where this stands in priorities? Outstanding for 2 EE customers right now, and I'd imagine every cloud customer.

**Comment by gregbrunk** [comment]
The ability to drop env variables, including SMTP settings, into a text area in the settings ui is a story that could definitely be crafted and fit into the next (or current, if we bump something) milestone. I will await @ryw 's feedback on priority.

**Comment by vparekh94** [comment]
Agree that the ability to add all of those things is definitely a story, but I'd be fine with just hacking in a way to do SMTP side separately until we can get something more built out. 

Being able to throw email notifications without exposing credentials on task failures/successes is used by just about every customer and is currently something that is easy to set up in vanilla Airflow but not with Astronomer.

**Comment by schnie** [comment]
Tracking this here now: https://github.com/astronomerio/astronomer-ee/issues/117
