### ISSUE TITLE
Cloud Feature Request: Have a NAT or single IP per deployment

### ISSUE THREAD

**Issue by petedejoy** [astronomerio/astronomer#153]
Requested by prospect- dealbreaker for them that they can't have their own IP to whitelist.

**Comment by petedejoy** [comment]
Just adding that now 3 prospects have requested this.

**Comment by petedejoy** [comment]
Per @schnie: In cloud, we run a single NAT that all internet bound traffic flows through, not at a customer level. We pretty much run solely at the Kubernetes layer and Kubernetes doesn't have a NAT resource or anything like that and it prob shouldn't. To deploy NATs we need to drop a layer down in terms of the things that Astronomer manages. We have a lot of plans to drop down after we nail the things we need to do at the Kubernetes layer. Sounds like a good future feature, but for now the best thing we can do is run it on their cloud

**Comment by ryw** [comment]
Issue moved to [astronomerio/astronomer-ce #3](https://github.com/astronomerio/astronomer-ce/issues/3) via [**ZenHub**](https://www.zenhub.com/)
