### ISSUE TITLE
Enterprise Feature Request: Ability to View All Image Tags

### ISSUE THREAD

**Issue by andscoop** [astronomerio/astronomer#154]
Since we have moved the private registry behind the token auth, it is not convenient to view a deployment's image tags, as well as when they were pushed. It would be nice to have the ability to view these through the platform and the CLI, as well as rolling back to any of the previous tags.

**Comment by ryw** [comment]
Issue moved to [astronomerio/astronomer-ee #134](https://github.com/astronomerio/astronomer-ee/issues/134) via [**ZenHub**](https://www.zenhub.com/)
