### ISSUE TITLE
Import Variables as File doesn't work

### ISSUE THREAD

**Issue by vparekh94** [astronomerio/astronomer#159]
When attempting to import variables from the "Choose File" button from the UI, the import fails without an error message. This can make initializing environments difficult.

Has anyone else run into this issue before?

**Comment by schnie** [comment]
@vparekh94 Any errors in the webserver logs?

**Comment by ryw** [comment]
Issue moved to [astronomerio/incubator-airflow #30](https://github.com/astronomerio/incubator-airflow/issues/30) via [**ZenHub**](https://www.zenhub.com/)
