### ISSUE TITLE
Docs pages rendering 404: `ee-install-k8s-secrets`

### ISSUE THREAD

**Issue by paolaperaza** [astronomerio/astronomer#160]
Reported by Sam's Club. Breakdown of Issue:

1. ALL links in Pre-Requisites menu of [`ee-installation-general-kubernetes`](https://www.astronomer.io/docs/ee-installation-general-kubernetes/) 404 upon initial click from the page (in new tab)

2. ALL work on refresh except:

- [`ee-install-k8s-secrets`](https://www.astronomer.io/docs/ee-install-k8s-secrets) 
- [`ee-installation-dev-env`](https://www.astronomer.io/guides/ee-installation-dev-env)

**Comment by paolaperaza** [comment]
@petedejoy They were given the general install link, with the rest of the links above being linked out from there in that menu of pre-requisites: https://www.astronomer.io/docs/ee-installation-general-kubernetes

1. I CAN see [ee-installation-k8s-secrets](https://www.astronomer.io/docs/ee-installation-k8s-secrets/) but that's not what's linked out in that menu under `7. Set a few Kubernetes secrets`. Right now that links out to: https://www.astronomer.io/guides/install-k8s-secrets/, so looks like we just have to correct that link on the doc

2. https://www.astronomer.io/guides/install-dev-env/ DOES work standalone, but NOT when clicked into from the pre-requisites menu we're talking about above

**Comment by petedejoy** [comment]
Fixes have been merged, thanks @paolaperaza!
