### ISSUE TITLE
Airflow: Extract API Plugin from SaaS

### ISSUE THREAD

**Issue by ryw** [astronomerio/astronomer#2]
@cwurtz made [an API plugin](https://github.com/astronomerio/docker-airflow-saas/tree/master/plugins/api) which covers a few use cases (list dags, list dag runs, backfill using executor), but can be extended, that we want to add to our Airflow distribution.

Compare w/ functionality of https://github.com/teamclairvoyant/airflow-rest-api-plugin/blob/master/plugins/rest_api_plugin.py which just makes calls to the python cli.

**Comment by cwurtz** [comment]
Copied it to a new plugin repo: https://github.com/airflow-plugins/airflow_api_plugin

Need to have further discussion on how we'll integrate this into the EE product.  It is problematic to copy it into the base image as the user could overwrite it in their build.  We can't control whether or not it is loaded.  This leads us down the path of building it back into our fork, and/or trying to get it into the upstream.
