### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by pedromachados** [astronomerio/astronomer#32]
[README.md](https://github.com/astronomerio/astronomer/blob/master/README.md)

> Full documentation for using the images can be found here.

> The project is licensed under the Apache 2 license. For more information on the licenses for each of the individual Astronomer Platform components packaged in the images, please refer to the respective Astronomer Platform documentation for each component.

This URL returns 404: https://astronomerio.github.io/astronomer/

**Comment by schnie** [comment]
Thanks for the heads up. Fixed!
