### ISSUE TITLE
Consider pinning Celery to 4.0.2

### ISSUE THREAD

**Issue by tedmiston** [astronomerio/astronomer#37]
Currently we take any version of Celery `>=4.0.2`, however there is significant discussion on the Airflow Dev list of stability issues with the latest release of Celery (4.1.0) e.g., the recent thread "Airflow looses track of Dag Tasks" and the issue https://github.com/apache/incubator-airflow/pull/2806 where a core contrib recommended pinning to 4.0.

Our dependency is https://github.com/astronomerio/incubator-airflow/blob/148c8f4a26bcc1be745534e0a5981982202db66e/setup.py#L100-L103 via https://github.com/astronomerio/astronomer/blob/f03223f773c93cd09417044742722679dd8b97a8/docker/platform/airflow/Dockerfile#L26

The puckel/docker-airflow repo that we forked docker-airflow-saas and docker-airflow-clickstream from pins to `==4.0.2` as well.

https://github.com/puckel/docker-airflow/blob/ef712bccc2d68994c16f6851a065bb835a5d4f78/Dockerfile#L60

@schnie @andscoop @cwurtz @ryw I think we should pin to 4.0.2 like everyone else for now for similar reasons.  Anyone opposed to that?

**Comment by tedmiston** [comment]
Made a preemptive PR for this in https://github.com/astronomerio/incubator-airflow/pull/23

**Comment by ryw** [comment]
merged
