### ISSUE TITLE
Airflow: Can we get memory usage over time for a task?

### ISSUE THREAD

**Issue by ryw** [astronomerio/astronomer#4]
@tedmiston commented on [Fri Dec 15 2017](https://github.com/astronomerio/astronomer-delete/issues/59)

It might be possible to get this info through Flower or the Airflow statsd thing?

---

@tedmiston commented on [Mon Dec 18 2017](https://github.com/astronomerio/astronomer-delete/issues/59#issuecomment-352491402)

@schnie Can you add anything you've learned here recently?  I think you were working with statsd in Airflow.  Is there overlap with that and how we use Prometheus?

---

@schnie commented on [Wed Dec 20 2017](https://github.com/astronomerio/astronomer-delete/issues/59#issuecomment-353255415)

@tedmiston I don't have anything currently that will track memory usage at a task level over time, but I think we could get live monitoring of the celery workers into prometheus/grafana with cadvisor. I'll tinker around some more and report back.

**Comment by tedmiston** [comment]
Greg and I discussed this a while ago before the issue was migrated and it's not something we have immediate plans to change today.  We might do this in the long run, but closing for now.
