### ISSUE TITLE
Fix Airflow stats

### ISSUE THREAD

**Issue by schnie** [astronomerio/astronomer#40]
Our grafana dashboard for the scheduler/workers shows some inaccurate numbers. See: https://issues.apache.org/jira/browse/AIRFLOW-774.

We should fix those bugs on our fork, release it, and submit a PR to apache.

This is kind of important, but since people aren't actually using it in production, there are no complaints. We should get ahead of it.

**Comment by ryw** [comment]
Issue moved to [astronomerio/incubator-airflow #25](https://github.com/astronomerio/incubator-airflow/issues/25) via [**ZenHub**](https://www.zenhub.com/)
