### ISSUE TITLE
Airflow: Remove bash dependency from airflow image

### ISSUE THREAD

**Issue by ryw** [astronomerio/astronomer#6]
@schnie commented on [Sat Dec 09 2017](https://github.com/astronomerio/astronomer-delete/issues/51)

Our entrypoint script currently uses some bash features. It'd be nice if we could just use the default shell, BusyBox Ash. Removes another dependency and reduces surface area.

**Comment by schnie** [comment]
This would break the bash operator - whoops. Closing...
