### ISSUE TITLE
Migrate Vortex out of DC/OS to ?

### ISSUE THREAD

**Issue by andscoop** [astronomerio/astronomer#62]

**Comment by tedmiston** [comment]
Note: Amazon EMR only supports Python 2.7 so some code change may be required.

Dataproc on GCP supports Python 3 - https://stackoverflow.com/questions/45843960/how-to-run-python3-on-googles-dataproc-pyspark.

Time permitting, it might be worth trying both to see how features like (auto)scaling compare.

**Comment by tedmiston** [comment]
Per convo with Ry today, this is de-prioritized for now.
