### ISSUE TITLE
Add to Docs: How continuous deployment with Astronomer set up works, including CI builds/integration with github

### ISSUE THREAD

**Issue by rbradk** [astronomerio/astronomer#75]
We've heard this question from a few prospects and think it's relevant enough to add to docs. 

Can someone answer this/write the guide, and then add it to the docs site?

**Comment by schnie** [comment]
@rbradk the details will differ between CI/CD products, but at a high level, the process is basically the same.

1) Install the astronomer platform, using EE docs. One component of the installation is a [private docker registry](https://github.com/astronomerio/astronomer/blob/master/docker/vendor/registry/Dockerfile). The registry is exposed at `registry.baseDomain`, where `baseDomain` is the domain the user launched the platform at. When new imagse are pushed to this registry, they get deployed to the cluster (this is how the CLI works under the hood).
2) Set up a CI/CD pipeline using whatever tool you'd like. Most tools will have some sort of documentation on how to trigger the pipeline from an event from github, like a new tag/release, or push to a branch. In this pipeline, after any tests have been executed, you just need to run a few `docker` commands. A couple examples:
- https://circleci.com/docs/2.0/building-docker-images/
- https://documentation.codeship.com/pro/builds-and-configuration/image-registries/#custom--self-hosted-registry
Images should be tagged with this format `registry.baseDomain/<company_name>/airflow:<version>`, and the user/password will be generated when the platform is initially installed.

@andscoop @tedmiston @cwurtz feel free to add anything to this.

**Comment by cwurtz** [comment]
Probably be best to have them download the CLI in their CI build as the registry is currently password protected, and will eventually have checks if the user has permission to deploy.  They can do:

```
astro auth login -d {their domain}
astro airflow deploy {release_name}
```

Where `{their domain}` is their base domain, and `{release_name}` is their kubernetes release name.  The CLI will handle the rest.

**Comment by tedmiston** [comment]
We have a customer in Slack who has started down the path of running it on CircleCI already.  I spoke with him about a few weeks ago.  (Omitting the name here since this repo is public.)

**Comment by tedmiston** [comment]
I just started a branch for CI deploy docs with some basic information.

https://github.com/astronomerio/astronomer-ee/compare/ci-deploy

Here's what I wrote so far:

> ## Deploy via CI/CD
> 
> You can deploy DAGs with continuous integration / continuous deployment via the Astronomer CLI.
> 
> While this guide focuses on CircleCI, a similar setup can be accomplished using Travis CI, Jenkins, Codeship, TeamCity, GitLab CI/CD, or any other CI/CD system.
> 
> For background information and best practices on CI/CD, we recommend reading the article [*An Introduction to CI/CD Best Practices*](https://www.digitalocean.com/community/tutorials/an-introduction-to-ci-cd-best-practices) from DigitalOcean.
> 
> TODO: copy discussion from https://github.com/astronomerio/astronomer/issues/75
> 
> ```bash
> ...
> ```
> 

If we all agree, I'm thinking of pasting in what @cwurtz and @schnie wrote above as well.

To @cwurtz point, we could consider wire up the current CLI with something like [expect](https://likegeeks.com/expect-command/) or pass creds in with a pipe/redirect [like this](https://stackoverflow.com/questions/14392525/passing-arguments-to-an-interactive-program-non-interactively/14397049#14397049) pulled from environment variables today potentially with no CLI changes.

**Comment by schnie** [comment]
@rbradk So for now, without any further CLI modifications, they can follow the steps I listed above (edited to show `<release_name>`).

Would you agree @cwurtz?

**Comment by rbradk** [comment]
@schnie what needs to be true to close this issue out?

**Comment by schnie** [comment]
If @cwurtz gives a thumbs up, then I think we just point them to their own CI/CD tools docs. There really shouldn't be anything Astro specific here, just standard docker stuff.

**Comment by cwurtz** [comment]
Greg's recommendation is the way to go right now
