### ISSUE TITLE
Document How and Why A User Could Build From astronomerinc/ap-base directly

### ISSUE THREAD

**Issue by andscoop** [astronomerio/astronomer#93]
In the case of individual needs that are not met by the `astronomerinc/ap-airflow:latest-onbuild` docker image, a user can build from `astronomerinc/ap-base directly. This will allow them to implement as much or as little of the logic in https://github.com/astronomerio/astronomer/blob/master/docker/platform/airflow/Dockerfile as well as their own custom logic.

In this documentation it would probably be best to point out the logic and reasoning behind all of the commands we run in the file currently. This will allow user to make educated decisions when implementing their new image.

**Comment by tedmiston** [comment]
Sent some feedback on the PR
