### ISSUE TITLE
Instructions on how to setup local users

### ISSUE THREAD

**Issue by dotcomputercraft** [astronomerio/astronomer#96]
hi, I love to install this system locally but I do not see instructions on how to setup the users for local Astronomer Enterprise Edition using the docker setup .  I looked here (https://open.astronomer.io/index.html) for instructions but did not find how to do it. can you help me?

**Comment by schnie** [comment]
Hey @dotcomputercraft, this repo has some docker-compose examples on how the images can be hooked together to create a production setup, but we don't recommend that for a production deployment. Enterprise users typically deploy via our helm charts for Kubernetes. Those charts live here: https://github.com/astronomerio/helm.astronomer.io.

Docs for enterprise exist at https://enterprise.astonomer.io. They're a bit scattered at the moment, but we'll be fixing those up soon!

**Comment by ryw** [comment]
@dotcomputercraft drop me an email (ry at astronomer dot io) if you'd like a call/demo of Astronomer EE
